# Generated by Django 4.2.6 on 2023-11-22 09:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name="Client's phone")),
                ('booking_date', models.DateField(verbose_name='Book day')),
                ('start_time', models.TimeField(verbose_name='Time of start')),
                ('end_time', models.TimeField(verbose_name='Time of end')),
                ('status', models.CharField(choices=[('pending', 'wait to confirm'), ('confirmed', 'accepted'), ('completed', 'finished'), ('canceled', 'canceled')], max_length=40, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
