# Generated by Django 4.2.6 on 2023-11-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Book day')),
                ('start_time', models.TimeField(verbose_name='Time of start')),
                ('end_time', models.TimeField(verbose_name='Time of end')),
                ('status', models.CharField(choices=[('pending', 'wait to confirm'), ('confirmed', 'accepted'), ('completed', 'finished'), ('canceled', 'canceled')], max_length=40, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
