# Generated by Django 4.2.6 on 2023-11-20 12:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='foreign_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name="Client's phone"),
        ),
    ]
