# Generated by Django 4.2.6 on 2023-11-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name, Phone or Email'),
        ),
    ]
