# Generated by Django 4.2.6 on 2024-03-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name': 'Work hour', 'verbose_name_plural': 'Work hours'},
        ),
    ]
