# Generated by Django 4.2.6 on 2024-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workhours', '0003_daycontrol_alter_workhours_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycontrol',
            options={'verbose_name': 'Day', 'verbose_name_plural': 'Days settings'},
        ),
        migrations.AlterField(
            model_name='daycontrol',
            name='close',
            field=models.TimeField(blank=True, null=True, verbose_name='Close hours'),
        ),
        migrations.AlterField(
            model_name='daycontrol',
            name='open',
            field=models.TimeField(blank=True, null=True, verbose_name='Open hours'),
        ),
    ]
