# Generated by Django 4.2.6 on 2024-01-23 08:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_siteuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Newbie', 'Новичок'), ('Amateur', 'Любитель'), ('Professional', 'Профессионал'), ('Master', 'Мастер')], max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Юзернейм, Телефон или Адрес электронной почты'),
        ),
    ]
