# Generated by Django 4.2.6 on 2024-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_siteuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='Логин'),
        ),
    ]
