# Generated by Django 4.2.6 on 2024-02-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_siteuser_options_alter_siteuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='emails',
            new_name='email',
        ),
    ]
