name: lint&tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  DB: 'lite'
  REDIS_HOST: '0.0.0.0'
  REDIS_PORT: '6379'
  
jobs:
  container_job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 6379:6379
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Create virtual environment
        run: python -m venv venv
      - name: Activate virtual environment
        run: source venv/bin/activate
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r req/dev.txt
      - name: Apply migrations
        run: |
          python manage.py migrate
      - name: Run linter
        run: |
          flake8 --exclude=static,*migrations,venv,config
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
